/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconsIconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconsIconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconsIconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconsIconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconsIconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    Mars3d: typeof import('./../components/mars3d/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiStackedCards: typeof import('./../components/ui/stacked-cards/index.vue')['default']
  }
}
