/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DefineComponent: typeof import('vue')['DefineComponent']
    IconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    Mars3dScene: typeof import('./../components/mars3d-scene/index.vue')['default']
    SearchBar: typeof import('./../components/ui/search-bar/index.vue')['default']
    StackedCards: typeof import('./../components/ui/stacked-cards/index.vue')['default']
  }
}
